# config
# cover: //blog.ghost.org/content/images/2013/Nov/cover.png
# logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'A developer, hacker, traveler and boarder live in New York. You can follow my code at '

# Content
excerpt_link: Read More

# Miscellaneous
rss:
